### ISSUE TITLE
Error because of missing editor.background and editor.foreground styles in some themes

### ISSUE THREAD

**Issue by markvaneijk** [phikiphp/phiki#26]
I encountered in some themes an error because of missing editor.background and editor.foreground styles.

Because some themes don't provide these values, I quickly fixed it using a `?? ''`:

https://github.com/markvaneijk/phiki/commit/5197daff3666aea3f1740ee74c43cbdf974aac12#diff-4ab344b68f2501a5180f1bb32aa615dc49980a150c59a864022af670d4438d15

**Comment by ryangjchandler** [comment]
Yep, this is a good shout. I've been testing with themes that had those values defined, so didn't catch this one.

**Comment by ryangjchandler** [comment]
Properties are now nullable so will default to whatever the CSS for the `pre`/`code` block uses.
