### ISSUE TITLE
Code blocks without a language defined gives error

### ISSUE THREAD

**Issue by markvaneijk** [phikiphp/phiki#27]
There is an error when you're not defining a language at the beginning of the code blocks, then you get an error that says something like "no txt grammar".

Fixed it the easy way by defining "txt" as an alias of "shellscript": https://github.com/markvaneijk/phiki/commit/19137c5ffb9b4e5717c85a4af041374de180d691

**Comment by ryangjchandler** [comment]
Ah, the `txt` grammar / empty grammar object must've disappeared when I added all of the Shiki grammars and themes, good spot!

**Comment by ryangjchandler** [comment]
Added `txt` back into the mix.
