### ISSUE TITLE
Some Themes are breaking when trying to use them

### ISSUE THREAD

**Issue by awcodes** [phikiphp/phiki#36]
Several of the themes are throwing an error.

For example, NightOwl and MaterialThemePalenight
```blade
{!! str($content)->markdown(extensions: [new PhikiExtension(Theme::NightOwl)]) !!}
```

https://flareapp.io/share/x5M1KeM5

**Comment by ryangjchandler** [comment]
Fixed in v0.2.9 @awcodes 👍
